---
- name: Autogen bcg729 library
  notify: Install bcg729 library
  command: cmake .
  args:
      chdir: "{{bcg729_path}}"
      creates: "{{bcg729_path}}/configure"

- name: Build bcg729 library
  notify: Install bcg729 library
  command: make
  args:
      chdir: "{{bcg729_path}}"
      creates: "{{bcg729_path}}/src/.libs/libbcg729.so"

- name: Install bcg729 library
  become: true
  command: make install
  args:
      chdir: "{{bcg729_path}}"
      creates: "/usr/local/lib/libbcg729.so"
